#!/bin/bash 
#### 
# Environment setting script. Automatically generated by Bake
####

echo "> Call with . bakeSetEnv.sh or source bakeSetEnv.sh"
 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/leonardo/dce-quagga/build/lib
 export PATH=$PATH:/home/leonardo/dce-quagga/build/bin
 export PYTHONPATH=$PYTHONPATH:/home/leonardo/bake:/home/leonardo/dce-quagga/build/lib:/home/leonardo/dce-quagga/build/lib/python2.7/dist-packages
 export INSTALL_BASE=/home/leonardo/dce-quagga/build
